apiVersion: v1
kind: Service
metadata:
  name: {{ template "mssql.fullname" . }}
  labels:
    app: {{ template "mssql.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.service.headless }}
  type: ClusterIP
  clusterIP: None
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: mssql
    port: {{ .Values.service.port }}
    targetPort: mssql
    {{- if and (eq "NodePort" .Values.service.type) .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    protocol: TCP
  selector:
    app: {{ template "mssql.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mssql.fullname" . }}-nodeport
  labels:
    app: {{ template "mssql.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  namespace: mssql
spec:
  selector:
    app: {{ template "mssql.name" . }}
    release: {{ .Release.Name }}
  type: NodePort
  ports:
    - name: mssql
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
      nodePort: 31433
  sessionAffinity: None
